echo "HELLO WORLD"

export PATH=/opt/homebrew/bin:$PATH

# sources bash_rc
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# ============
# Additional files to add to .bash_profile
source ~/dotfiles/bash/bash_config
source ~/dotfiles/bash/bash_aliases
source ~/dotfiles/bash/bash_prompt
