# set up aliases
# --------------
# for git
alias g="git status"	# status of files
alias ga="git add"		# add a file to staging
alias gr="git rm" 		# remove a file 
alias gc="git commit -m"	# commit files to repo
alias gp="git push"		# push to repo
alias gpl="git pull"	# pull from repo
alias gpom="git push origin master" # typically to send to github
alias gpod="git push origin dev" # typically to send the dev branch to github
alias gplom="git pull origin master" # typically to get master from github
alias gplod="git pull origin dev" # typically to get the dev branch from github
alias gphm="git push heroku master" # typically to send to heroku
alias gco="git checkout" # checkout
alias gcom="git checkout master" # checkout master branch
alias gcod="git checkout dev" # checkout dev branch
alias gcl="git clone"	# invoking clone command
alias gb="git branch"	# for branching
alias gm="git merge"	# for merging
alias gl="git gl"			# pretty log (specs in .gitconfig)

# --------------
# for command line
alias ls="ls -G"
alias cdls='cd $1 && ls'

# ------------
# for nvim 
alias vi='nvim'
alias vim='nvim'

# ------------
# for python
alias py3='python3'

